import PySide2.QtGui.QVector4D
import PySide2.QtGui.QVector3D
import PySide2.QtGui.QVector2D
import PySide2.QtGui.QTouchDevice
import PySide2.QtGui.QTextTableCell
import PySide2.QtGui.QTextOption
import PySide2.QtGui.QTextObjectInterface
import PySide2.QtGui.QTextLine
import PySide2.QtGui.QTextLength
import PySide2.QtGui.QTextItem
import PySide2.QtGui.QTextInlineObject
import PySide2.QtGui.QTextFragment
import PySide2.QtGui.QTextFormat
import PySide2.QtGui.QTextListFormat
import PySide2.QtGui.QTextFrameFormat
import PySide2.QtGui.QTextTableFormat
import PySide2.QtGui.QTextCursor
import PySide2.QtGui.QTextBlockUserData
import PySide2.QtGui.QTextBlockFormat
import PySide2.QtGui.QTextBlock
import PySide2.QtGui.QSurfaceFormat
import PySide2.QtGui.QSurface
import PySide2.QtGui.QQuaternion
import PySide2.QtGui.QPolygonF
import PySide2.QtGui.QPolygon
import PySide2.QtGui.QPointingDeviceUniqueId
import PySide2.QtGui.QPixmapCache
import PySide2.QtGui.QPixelFormat
import PySide2.QtGui.QPictureIO
import PySide2.QtGui.QPalette
import PySide2.QtGui.QPainterPathStroker
import PySide2.QtGui.QPaintEngineState
import PySide2.QtGui.QPaintDevice
import PySide2.QtGui.QPicture
import PySide2.QtGui.QPagedPaintDevice
import PySide2.QtGui.QPageSize
import PySide2.QtGui.QOpenGLVersionProfile
import PySide2.QtGui.QOpenGLTextureBlitter
import PySide2.QtGui.QOpenGLTexture
import PySide2.QtGui.QOpenGLPixelTransferOptions
import PySide2.QtGui.QOpenGLFunctions
import PySide2.QtGui.QOpenGLFramebufferObjectFormat
import PySide2.QtGui.QOpenGLFramebufferObject
import PySide2.QtGui.QOpenGLExtraFunctions
import PySide2.QtGui.QOpenGLDebugMessage
import PySide2.QtGui.QOpenGLBuffer
import PySide2.QtGui.QMatrix4x4
import PySide2.QtGui.QMatrix
import PySide2.QtGui.QKeySequence
import PySide2.QtGui.QImageIOHandler
import PySide2.QtGui.QGradient
import PySide2.QtGui.QLinearGradient
import PySide2.QtGui.QRadialGradient
import PySide2.QtGui.QMatrix4x3
import PySide2.QtGui.QMatrix4x2
import PySide2.QtGui.QMatrix3x4
import PySide2.QtGui.QMatrix3x3
import PySide2.QtGui.QMatrix3x2
import PySide2.QtGui.QMatrix2x4
import PySide2.QtGui.QMatrix2x3
import PySide2.QtGui.QMatrix2x2
import PySide2.QtGui.QFontMetricsF
import PySide2.QtGui.QFontMetrics
import PySide2.QtGui.QFontInfo
import PySide2.QtGui.QFontDatabase
import PySide2.QtGui.QFont
import PySide2.QtGui.QTextCharFormat
import PySide2.QtGui.QTextImageFormat
import PySide2.QtGui.QTextTableCellFormat
import PySide2.QtGui.QDesktopServices
import PySide2.QtGui.QCursor
import PySide2.QtGui.QConicalGradient
import PySide2.QtGui.QColor
import PySide2.QtGui.QAccessibleValueInterface
import PySide2.QtGui.QAccessibleTextInterface
import PySide2.QtGui.QAccessibleTableCellInterface
import PySide2.QtGui.QAccessibleEvent
import PySide2.QtGui.QAccessibleTextCursorEvent
import PySide2.QtGui.QAccessibleTextSelectionEvent
import PySide2.QtGui.QAccessibleTextRemoveEvent
import PySide2.QtGui.QAccessibleTextInsertEvent
import PySide2.QtGui.QAccessibleTextUpdateEvent
import PySide2.QtGui.QAccessibleTableModelChangeEvent
import PySide2.QtGui.QAccessibleStateChangeEvent
import PySide2.QtGui.QAccessibleValueChangeEvent
import PySide2.QtGui.QAccessibleEditableTextInterface
import PySide2.QtGui.QAccessible
import PySide2.QtGui.QAccessibleInterface
import PySide2.QtGui.QAccessibleObject
import PySide2.QtGui.QAbstractOpenGLFunctions
import PySide2.QtGui.QTransform
import PySide2.QtGui.QRawFont
import PySide2.QtGui.QStaticText
import PySide2.QtGui.QBrush
import PySide2.QtGui.QStandardItem
import PySide2.QtGui.QPen
import PySide2.QtGui.QPainterPath
import PySide2.QtGui.QPaintEngine
import PySide2.QtGui.QIcon
import PySide2.QtGui.QIconEngine
import PySide2.QtGui.QTextLayout
import PySide2.QtGui.QPixmap
import PySide2.QtGui.QImage
import PySide2.QtGui.QBitmap
import PySide2.QtGui.QPainter
import PySide2.QtGui.QBackingStore
import PySide2.QtGui.QPageLayout
import PySide2.QtGui.QOpenGLTimerQuery
import PySide2.QtGui.QOpenGLTimeMonitor
import PySide2.QtGui.QOpenGLShaderProgram
import PySide2.QtGui.QOpenGLShader
import PySide2.QtGui.QClipboard
import PySide2.QtGui.QOpenGLDebugLogger
import PySide2.QtGui.QOpenGLContextGroup
import PySide2.QtGui.QOpenGLContext
import PySide2.QtGui.QOffscreenSurface
import PySide2.QtGui.QSyntaxHighlighter
import PySide2.QtGui.QStyleHints
import PySide2.QtGui.QAbstractTextDocumentLayout
import PySide2.QtGui.QSessionManager
import PySide2.QtGui.QScreen
import PySide2.QtGui.QInputMethod
import PySide2.QtGui.QPyTextObject
import PySide2.QtGui.QWindow
import PySide2.QtGui.QPaintDeviceWindow
import PySide2.QtGui.QOpenGLWindow
import PySide2.QtGui.QRasterWindow
import PySide2.QtGui.QPdfWriter
import PySide2.QtGui.QValidator
import PySide2.QtGui.QDoubleValidator
import PySide2.QtGui.QIntValidator
import PySide2.QtGui.QRegExpValidator
import PySide2.QtGui.QTextObject
import PySide2.QtGui.QTextBlockGroup
import PySide2.QtGui.QTextList
import PySide2.QtGui.QTextFrame
import PySide2.QtGui.QTextTable
import PySide2.QtGui.QDrag
import PySide2.QtGui.QOpenGLVertexArrayObject
import PySide2.QtGui.QHideEvent
import PySide2.QtGui.QHelpEvent
import PySide2.QtGui.QMoveEvent
import PySide2.QtGui.QFocusEvent
import PySide2.QtGui.QFileOpenEvent
import PySide2.QtGui.QExposeEvent
import PySide2.QtGui.QWindowStateChangeEvent
import PySide2.QtGui.QEnterEvent
import PySide2.QtGui.QDropEvent
import PySide2.QtGui.QDragMoveEvent
import PySide2.QtGui.QDragEnterEvent
import PySide2.QtGui.QWhatsThisClickedEvent
import PySide2.QtGui.QPaintEvent
import PySide2.QtGui.QDragLeaveEvent
import PySide2.QtGui.QStatusTipEvent
import PySide2.QtGui.QToolBarChangeEvent
import PySide2.QtGui.QShowEvent
import PySide2.QtGui.QInputMethodQueryEvent
import PySide2.QtGui.QCloseEvent
import PySide2.QtGui.QShortcutEvent
import PySide2.QtGui.QInputMethodEvent
import PySide2.QtGui.QScrollPrepareEvent
import PySide2.QtGui.QInputEvent
import PySide2.QtGui.QWheelEvent
import PySide2.QtGui.QKeyEvent
import PySide2.QtGui.QNativeGestureEvent
import PySide2.QtGui.QContextMenuEvent
import PySide2.QtGui.QTabletEvent
import PySide2.QtGui.QMouseEvent
import PySide2.QtGui.QTouchEvent
import PySide2.QtGui.QHoverEvent
import PySide2.QtGui.QScrollEvent
import PySide2.QtGui.QActionEvent
import PySide2.QtGui.QResizeEvent
import PySide2.QtGui.QIconDragEvent
import PySide2.QtGui.QRegion
import PySide2.QtGui.QGuiApplication
import PySide2.QtGui.QTextDocument
import PySide2.QtGui.QMovie
import PySide2.QtGui.QImageWriter
import PySide2.QtGui.QImageReader
import PySide2.QtGui.QTextDocumentWriter
import PySide2.QtGui.QTextDocumentFragment
import PySide2.QtGui.QStandardItemModel
import PySide2.QtWidgets.QWhatsThis
import PySide2.QtWidgets.QUndoCommand
import PySide2.QtWidgets.QTreeWidgetItemIterator
import PySide2.QtWidgets.QTreeWidgetItem
import PySide2.QtWidgets.QToolTip
import PySide2.QtWidgets.QTableWidgetSelectionRange
import PySide2.QtWidgets.QTableWidgetItem
import PySide2.QtWidgets.QStyleOption
import PySide2.QtWidgets.QStyleOptionGraphicsItem
import PySide2.QtWidgets.QStyleOptionViewItem
import PySide2.QtWidgets.QStyleOptionFrame
import PySide2.QtWidgets.QStyleOptionFocusRect
import PySide2.QtWidgets.QStyleOptionToolBox
import PySide2.QtWidgets.QStyleOptionDockWidget
import PySide2.QtWidgets.QStyleOptionToolBar
import PySide2.QtWidgets.QStyleOptionComplex
import PySide2.QtWidgets.QStyleOptionToolButton
import PySide2.QtWidgets.QStyleOptionTitleBar
import PySide2.QtWidgets.QStyleOptionComboBox
import PySide2.QtWidgets.QStyleOptionSpinBox
import PySide2.QtWidgets.QStyleOptionSlider
import PySide2.QtWidgets.QStyleOptionSizeGrip
import PySide2.QtWidgets.QStyleOptionGroupBox
import PySide2.QtWidgets.QStyleOptionTabWidgetFrame
import PySide2.QtWidgets.QStyleOptionButton
import PySide2.QtWidgets.QStyleOptionTabBarBase
import PySide2.QtWidgets.QStyleOptionTab
import PySide2.QtWidgets.QStyleOptionRubberBand
import PySide2.QtWidgets.QStyleOptionProgressBar
import PySide2.QtWidgets.QStyleOptionMenuItem
import PySide2.QtWidgets.QStyleOptionHeader
import PySide2.QtWidgets.QStyleHintReturn
import PySide2.QtWidgets.QStyleHintReturnVariant
import PySide2.QtWidgets.QStyleHintReturnMask
import PySide2.QtWidgets.QStyleFactory
import PySide2.QtWidgets.QSizePolicy
import PySide2.QtWidgets.QScrollerProperties
import PySide2.QtWidgets.QListWidgetItem
import PySide2.QtWidgets.QItemEditorFactory
import PySide2.QtWidgets.QItemEditorCreatorBase
import PySide2.QtWidgets.QGestureRecognizer
import PySide2.QtWidgets.QFileIconProvider
import PySide2.QtWidgets.QColormap
import PySide2.QtWidgets.QAccessibleWidget
import PySide2.QtWidgets.QLayoutItem
import PySide2.QtWidgets.QWidgetItem
import PySide2.QtWidgets.QSpacerItem
import PySide2.QtWidgets.QTileRules
import PySide2.QtWidgets.QGraphicsLayoutItem
import PySide2.QtWidgets.QGraphicsLayout
import PySide2.QtWidgets.QGraphicsAnchorLayout
import PySide2.QtWidgets.QGraphicsLinearLayout
import PySide2.QtWidgets.QGraphicsGridLayout
import PySide2.QtWidgets.QGraphicsItem
import PySide2.QtWidgets.QGraphicsPixmapItem
import PySide2.QtWidgets.QGraphicsLineItem
import PySide2.QtWidgets.QGraphicsItemGroup
import PySide2.QtWidgets.QAbstractGraphicsShapeItem
import PySide2.QtWidgets.QGraphicsSimpleTextItem
import PySide2.QtWidgets.QGraphicsPathItem
import PySide2.QtWidgets.QGraphicsRectItem
import PySide2.QtWidgets.QGraphicsPolygonItem
import PySide2.QtWidgets.QGraphicsEllipseItem
import PySide2.QtWidgets.QStylePainter
import PySide2.QtWidgets.QSystemTrayIcon
import PySide2.QtWidgets.QLayout
import PySide2.QtWidgets.QBoxLayout
import PySide2.QtWidgets.QVBoxLayout
import PySide2.QtWidgets.QHBoxLayout
import PySide2.QtWidgets.QFormLayout
import PySide2.QtWidgets.QGridLayout
import PySide2.QtWidgets.QStackedLayout
import PySide2.QtWidgets.QDataWidgetMapper
import PySide2.QtWidgets.QCompleter
import PySide2.QtWidgets.QGraphicsTransform
import PySide2.QtWidgets.QGraphicsScale
import PySide2.QtWidgets.QGraphicsRotation
import PySide2.QtWidgets.QButtonGroup
import PySide2.QtWidgets.QPlainTextDocumentLayout
import PySide2.QtWidgets.QActionGroup
import PySide2.QtWidgets.QAction
import PySide2.QtWidgets.QWidgetAction
import PySide2.QtWidgets.QAbstractItemDelegate
import PySide2.QtWidgets.QItemDelegate
import PySide2.QtWidgets.QStyledItemDelegate
import PySide2.QtWidgets.QStyle
import PySide2.QtWidgets.QCommonStyle
import PySide2.QtWidgets.QProxyStyle
import PySide2.QtWidgets.QGraphicsScene
import PySide2.QtWidgets.QGraphicsObject
import PySide2.QtWidgets.QGraphicsTextItem
import PySide2.QtWidgets.QGraphicsWidget
import PySide2.QtWidgets.QGraphicsProxyWidget
import PySide2.QtWidgets.QUndoStack
import PySide2.QtWidgets.QShortcut
import PySide2.QtWidgets.QUndoGroup
import PySide2.QtWidgets.QScroller
import PySide2.QtWidgets.QGraphicsItemAnimation
import PySide2.QtWidgets.QGraphicsEffect
import PySide2.QtWidgets.QGraphicsOpacityEffect
import PySide2.QtWidgets.QGraphicsDropShadowEffect
import PySide2.QtWidgets.QGraphicsColorizeEffect
import PySide2.QtWidgets.QGraphicsBlurEffect
import PySide2.QtWidgets.QGraphicsAnchor
import PySide2.QtWidgets.QGesture
import PySide2.QtWidgets.QPinchGesture
import PySide2.QtWidgets.QPanGesture
import PySide2.QtWidgets.QTapGesture
import PySide2.QtWidgets.QTapAndHoldGesture
import PySide2.QtWidgets.QSwipeGesture
import PySide2.QtWidgets.QGestureEvent
import PySide2.QtWidgets.QGraphicsSceneEvent
import PySide2.QtWidgets.QGraphicsSceneWheelEvent
import PySide2.QtWidgets.QGraphicsSceneResizeEvent
import PySide2.QtWidgets.QGraphicsSceneMoveEvent
import PySide2.QtWidgets.QGraphicsSceneMouseEvent
import PySide2.QtWidgets.QGraphicsSceneHoverEvent
import PySide2.QtWidgets.QGraphicsSceneHelpEvent
import PySide2.QtWidgets.QGraphicsSceneDragDropEvent
import PySide2.QtWidgets.QGraphicsSceneContextMenuEvent
import PySide2.QtWidgets.QWidget
import PySide2.QtWidgets.QDockWidget
import PySide2.QtWidgets.QDialogButtonBox
import PySide2.QtWidgets.QDialog
import PySide2.QtWidgets.QDesktopWidget
import PySide2.QtWidgets.QComboBox
import PySide2.QtWidgets.QColorDialog
import PySide2.QtWidgets.QCalendarWidget
import PySide2.QtWidgets.QAbstractSpinBox
import PySide2.QtWidgets.QDateTimeEdit
import PySide2.QtWidgets.QDateEdit
import PySide2.QtWidgets.QAbstractSlider
import PySide2.QtWidgets.QDial
import PySide2.QtWidgets.QStatusBar
import PySide2.QtWidgets.QAbstractButton
import PySide2.QtWidgets.QCheckBox
import PySide2.QtWidgets.QSplitterHandle
import PySide2.QtWidgets.QSplashScreen
import PySide2.QtWidgets.QSpinBox
import PySide2.QtWidgets.QSlider
import PySide2.QtWidgets.QSizeGrip
import PySide2.QtWidgets.QScrollBar
import PySide2.QtWidgets.QRubberBand
import PySide2.QtWidgets.QRadioButton
import PySide2.QtWidgets.QPushButton
import PySide2.QtWidgets.QCommandLinkButton
import PySide2.QtWidgets.QProgressDialog
import PySide2.QtWidgets.QProgressBar
import PySide2.QtWidgets.QOpenGLWidget
import PySide2.QtWidgets.QMessageBox
import PySide2.QtWidgets.QMenuBar
import PySide2.QtWidgets.QMenu
import PySide2.QtWidgets.QMdiSubWindow
import PySide2.QtWidgets.QMainWindow
import PySide2.QtWidgets.QLineEdit
import PySide2.QtWidgets.QKeySequenceEdit
import PySide2.QtWidgets.QInputDialog
import PySide2.QtWidgets.QGroupBox
import PySide2.QtWidgets.QWizardPage
import PySide2.QtWidgets.QWizard
import PySide2.QtWidgets.QToolButton
import PySide2.QtWidgets.QToolBar
import PySide2.QtWidgets.QTimeEdit
import PySide2.QtWidgets.QFrame
import PySide2.QtWidgets.QToolBox
import PySide2.QtWidgets.QSplitter
import PySide2.QtWidgets.QLabel
import PySide2.QtWidgets.QLCDNumber
import PySide2.QtWidgets.QAbstractScrollArea
import PySide2.QtWidgets.QAbstractItemView
import PySide2.QtWidgets.QHeaderView
import PySide2.QtWidgets.QColumnView
import PySide2.QtWidgets.QTreeView
import PySide2.QtWidgets.QTreeWidget
import PySide2.QtWidgets.QListView
import PySide2.QtWidgets.QUndoView
import PySide2.QtWidgets.QListWidget
import PySide2.QtWidgets.QScrollArea
import PySide2.QtWidgets.QMdiArea
import PySide2.QtWidgets.QGraphicsView
import PySide2.QtWidgets.QStackedWidget
import PySide2.QtWidgets.QTableView
import PySide2.QtWidgets.QTableWidget
import PySide2.QtWidgets.QFontDialog
import PySide2.QtWidgets.QTabWidget
import PySide2.QtWidgets.QFontComboBox
import PySide2.QtWidgets.QTabBar
import PySide2.QtWidgets.QFocusFrame
import PySide2.QtWidgets.QErrorMessage
import PySide2.QtWidgets.QDoubleSpinBox
import PySide2.QtWidgets.QApplication
import PySide2.QtWidgets.QPlainTextEdit
import PySide2.QtWidgets.QTextEdit
import PySide2.QtWidgets.QTextBrowser
import PySide2.QtWidgets.QFileDialog
import PySide2.QtWidgets.QKeyEventTransition
import PySide2.QtWidgets.QMouseEventTransition
import PySide2.QtWidgets.QFileSystemModel
import PySide2.QtWidgets.QDirModel
